version: '3'

services:
  redis:
    image: redis:5-alpine
  rq:
    build: .
    command: python manage.py rqworker
    volumes:
      - .:/code
    env_file:
      - app.env
    depends_on:
      - redis
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn upicollect.wsgi:application --bind 0.0.0.0:8000 -w 8 --access-logfile - --error-logfile -
    volumes:
      - .:/code
    env_file:
      - app.env
    ports:
      - "0.0.0.0:80:8000"
    depends_on:
      - rq