# Generated by Django 2.2.6 on 2019-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0002_auto_20191019_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
