# Generated by Django 2.2.6 on 2019-10-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0011_auto_20191019_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
