# Generated by Django 2.2.6 on 2019-10-19 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0011_auto_20191019_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cycle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='cycle_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='frequency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cycle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
