# Generated by Django 2.2.6 on 2019-10-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0012_auto_20191019_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
    ]
