# Generated by Django 2.2.6 on 2019-10-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0013_remove_subscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
